In [1]:
import numpy as np
import pandas as pd

In [2]:
Gadi = [189.64,114.34,136.7,139.22,96.64,84.7,144.98,121.36]
Mey = [114.34,151.08,137.16,124.16,99.22,109.78,135.72,138.72,165] 
Suds = [113.74,117.9,147.7,130.7,124.1,128.88,117.76,123.16,83.32]
Must = [99.04,112.94,141.22,155.06,124.5,154.36,83.36,145.68,131.10]
Bach = [125.38,115.76,95.82,123.36,158.84,153.1,121.18,129.26]
Subh = [117.76,115.00,90.94,128.26,108.34,135.14,150.54,116.46,132.46]
Dhak = [143.76,110.06,136.94,115.98,141.9,133.98,119.04,142.80,91.38]
Bharg = [124.84,115.8,94.3,151.62,93.58,91.5,126.36,156.46,133.58]
Saad = [81.42,151.94,84.68,119.28,109.82,155.88,101.92,147.62,129.90]
Chai = [126.96,142.12,110.54,109.28,158.3,131.9,112.32,63.44,148.44]
Freeman = {"Subh":Subh, "Must":Must, "Dhak":Dhak, "Chai":Chai, "Bach":Bach,\
        "Saad":Saad, "Bharg":Bharg, "Gadi":Gadi, "Suds":Suds, "Mey":Mey,}

In [3]:
Gadi = ["Suds","Subh","Chai","Dhak","Saad","Must","Bharg","Bach","Mey"]
Mey = ["Subh","Chai","Dhak","Bach","Bharg","Suds","Saad","Must","Gadi"]
Suds = ["Gadi","Dhak","Subh","Saad","Chai","Mey","Must","Bharg","Bach"]
Must = ["Saad","Bach","Bharg","Chai","Dhak","Gadi","Suds","Mey","Subh"]
Bach = ["Bharg","Must","Saad","Mey","Subh","Chai","Dhak","Gadi","Suds"]
Subh = ["Mey","Gadi","Suds","Bharg","Bach","Saad","Chai","Dhak","Must"]
Dhak = ["Chai","Suds","Mey","Gadi","Must","Bharg","Bach","Subh","Saad"]
Bharg = ["Bach","Saad","Must","Subh","Mey","Dhak","Gadi","Suds","Chao"]
Saad = ["Must","Bharg","Bach","Suds","Gadi","Subh","Mey","Chai"."Dhak"]
Chai = ["Dhak","Mey","Gadi","Must","Suds","Bach","Subh","Saad","Bharg"]
Freeman_sched = {"Subh":Subh, "Must":Must, "Dhak":Dhak, "Chai":Chai, "Bach":Bach,\
        "Saad":Saad, "Bharg":Bharg, "Gadi":Gadi, "Suds":Suds, "Mey":Mey,}

In [4]:
def two_step_dominance(X):
    '''Returns result of two step dominance formula'''
    X_sq = np.matmul(X,X)
    matrix = np.add(X_sq,X)
    result = [sum(x) for x in matrix]
    return result


def power_points(dominance, teams, week):
    '''Returns list of power points'''
    power_points = []
    for i, team in zip(dominance, teams):
        avg_score = sum(team.scores[:week]) / week
        avg_mov = sum(team.mov[:week]) / week

        power = '{0:.2f}'.format((int(i)*0.8) + (int(avg_score)*0.15) +
                                 (int(avg_mov)*0.05))
        power_points.append(power)
    power_tup = [(i, j) for (i, j) in zip(power_points, teams)]
    return sorted(power_tup, key=lambda tup: float(tup[0]), reverse=True)

In [5]:
win_df = pd.DataFrame(np.zeros(shape=(10,10)))
win_df.columns = Freeman.keys()
win_df.index = Freeman.keys()
win_mov = win_df.copy()
for team in Freeman_sched:
    ## loop through team
    opponents = Freeman_sched[team]
    ## loop through opponents for team 
    for week,opp in enumerate(opponents):
        #print(team + " vs. " + opp + " Week " + str(week))
        opp_score = Freeman[opp][week]
        team_score = Freeman[team][week]
        if team_score > opp_score:
            win_df[team][opp] += 1
            win_mov[team][opp] += team_score - opp_score

In [10]:
win_df

       Subh  Must  Dhak  Chai  Bach  Saad  Bharg  Gadi  Suds  Mey
Subh    0.0   0.0   0.0   0.0   1.0   1.0    1.0   0.0   1.0  0.0
Must    0.0   0.0   1.0   0.0   1.0   0.0    0.0   0.0   0.0  0.0
Dhak    0.0   0.0   0.0   0.0   0.0   0.0    0.0   1.0   1.0  1.0
Chai    0.0   1.0   1.0   0.0   1.0   0.0    0.0   1.0   0.0  1.0
Bach    0.0   0.0   0.0   0.0   0.0   0.0    0.0   0.0   0.0  1.0
Saad    0.0   1.0   0.0   0.0   1.0   0.0    0.0   0.0   1.0  0.0
Bharg   0.0   1.0   1.0   0.0   1.0   1.0    0.0   0.0   0.0  1.0
Gadi    1.0   1.0   0.0   0.0   0.0   1.0    0.0   0.0   0.0  0.0
Suds    0.0   0.0   0.0   1.0   0.0   0.0    0.0   1.0   0.0  0.0
Mey     1.0   0.0   0.0   0.0   0.0   0.0    0.0   0.0   1.0  0.0

In [6]:
win_array = np.array(win_df.T)

In [7]:
dominance_vec = two_step_dominance(win_array)

In [8]:
power_pts = []  
week = 4
for i,team in zip(dominance_vec,Freeman_sched.keys()):
    print(team)
    avg_score = sum(Freeman[team][:week])/week
    win_margin = win_mov[team].tolist()
    loss_margin = win_mov.loc[team].tolist()
    loss_margin = [-val for val in loss_margin]
    avg_mov = (sum(loss_margin) + sum(win_margin))/week
    print(i,avg_score,avg_mov)
    power = '{0:.2f}'.format((int(i)*0.8) + (int(avg_score)*0.15) +
                                 (int(avg_mov)*0.05))
    power_pts.append(power)
    power_tup = [(i, j) for (i, j) in zip(power_pts, Freeman_sched.keys())]

Subh
9.0 112.99 -36.82000000000001
Must
12.0 127.06500000000001 39.94
Dhak
9.0 126.685 11.344999999999999
Chai
5.0 122.225 -21.17499999999999
Bach
16.0 115.08 21.349999999999994
Saad
9.0 109.33000000000001 7.470000000000006
Bharg
3.0 121.64 -27.08999999999999
Gadi
11.0 144.975 10.449999999999992
Suds
16.0 127.50999999999999 -3.745000000000008
Mey
14.0 131.685 -1.7249999999999979

In [9]:
sorted(power_tup, key=lambda x: x[0],reverse=True)

[('31.70', 'Suds'),
 ('31.10', 'Bach'),
 ('30.90', 'Gadi'),
 ('30.80', 'Mey'),
 ('30.60', 'Must'),
 ('26.65', 'Dhak'),
 ('23.90', 'Saad'),
 ('22.20', 'Subh'),
 ('21.25', 'Chai'),
 ('19.20', 'Bharg')]